PIPS-NLP: Fix missing header bug in AMPL driver
This commit fixes the bug introduced in commit
07930126ad1d12af084143aa78f97f5d2ca9aa81 that manifests below when
building PIPS:

In file included from
/Users/oxberry1/PIPS/PIPS-NLP/Drivers/parallelAmplDriver.cpp:5:
/Users/oxberry1/PIPS/Input/amplGenStochInput.hpp:14:10: fatal error:
'par_macro.h' file not found
         ^
	 1 error generated.