PIPS-NLP: Fix bug due to bad par_macro header path
Fix bug introduced in commit 826ba3eee13d5487d60072589a8229a6fd0b7774
that adds PAR_DEBUG macro. Before this commit, the following errors
occurring during a PIPS build:

In file included from
PIPS/PIPS-NLP/Core/NlpInfo/sNlpInfoFromNL.C:24:
PIPS/Input/amplGenStochInput.hpp:14:10: fatal error:
'par_macro.h' file not found