Input: Add missing header for PAR_DEBUG macro
Fixes bugs introduced by commit
07930126ad1d12af084143aa78f97f5d2ca9aa81. Before this commit, the
following build system errors occurred:

In file included from PIPS/Input/amplGenStochInput.cpp:5:

PIPS/Input/amplGenStochInput.hpp:128:3: error: use of undeclared
identifier 'PAR_DEBUG' PAR_DEBUG("getFirstStageConstraints");

PIPS/Input/amplGenStochInput.hpp:134:46: error:
invalid operands to binary expression ('const char *' and 'int')
PAR_DEBUG("getSecondStageConstraints scen" << scen);

PIPS/Input/amplGenStochInput.hpp:140:42: error: invalid
operands to binary expression ('const char *' and 'int')
PAR_DEBUG("getLinkingConstraints scen" << scen);

PIPS/Input/amplGenStochInput.hpp:146:3: error: use of undeclared
identifier 'PAR_DEBUG' PAR_DEBUG("getFirstStageHessian");

PIPS/Input/amplGenStochInput.hpp:153:42: error: invalid
operands to binary expression ('const char *' and 'int')
PAR_DEBUG("getSecondStageHessian scen" << scen);

PIPS/Input/amplGenStochInput.hpp:161:47: error: invalid
operands to binary expression ('const char *' and 'int')
PAR_DEBUG("getSecondStageCrossHessian scen" << scen);

 6 errors generated.
make[2]: ***
[Input/CMakeFiles/genNLparallel.dir/amplGenStochInput.cpp.o] Error 1
make[1]: *** [Input/CMakeFiles/genNLparallel.dir/all] Error 2 make: ***
[all] Error 2